/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 vzscene.glb -T -S -t -k -R s
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    circle1_constant2_0: THREE.Mesh
    circle2_constant2_0: THREE.Mesh
    circle_constant1_0: THREE.Mesh
    circle_HoloFillDark_0: THREE.Mesh
    geo1_HoloFillDark_0_1: THREE.Mesh
    geo1_HoloFillDark_0_2: THREE.Mesh
    vzHumanoid: THREE.Mesh
    dome: THREE.Mesh
    medulaOrb: THREE.Mesh
    Sphere_Core_0: THREE.Mesh
    Sphere_Core_0001: THREE.Mesh
    Sphere_Core_0002: THREE.Mesh
    Sphere_Core_0003: THREE.Mesh
    Sphere_Core_0004: THREE.Mesh
    Sphere_Core_0005: THREE.Mesh
    Sphere_Core_0006: THREE.Mesh
    Sphere_Core_0007: THREE.Mesh
    Sphere_Core_0008: THREE.Mesh
    Sphere_Core_0009: THREE.Mesh
    Sphere_Core_0010: THREE.Mesh
    Sphere_Core_0011: THREE.Mesh
    Sphere_Core_0012: THREE.Mesh
    Sphere_Core_0013: THREE.Mesh
    Sphere_Core_0014: THREE.Mesh
    Sphere_Core_0015: THREE.Mesh
    Sphere_Core_0016: THREE.Mesh
    JNLogo: THREE.Mesh
  }
  materials: {
    constant2: THREE.MeshStandardMaterial
    constant1: THREE.MeshStandardMaterial
    HoloFillDark: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    Core: THREE.MeshStandardMaterial
    ['Core.001']: THREE.MeshStandardMaterial
  }
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/vzscene-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="scifiRotate" position={[-0.39, 12.05, -7.22]} scale={5}>
        <mesh name="circle1_constant2_0" geometry={nodes.circle1_constant2_0.geometry} material={materials.constant2} />
        <mesh name="circle2_constant2_0" geometry={nodes.circle2_constant2_0.geometry} material={materials.constant2} />
        <mesh name="circle_constant1_0" geometry={nodes.circle_constant1_0.geometry} material={materials.constant1} />
        <mesh name="circle_HoloFillDark_0" geometry={nodes.circle_HoloFillDark_0.geometry} material={materials.HoloFillDark} />
        <mesh name="geo1_HoloFillDark_0_1" geometry={nodes.geo1_HoloFillDark_0_1.geometry} material={materials.HoloFillDark} />
        <mesh name="geo1_HoloFillDark_0_2" geometry={nodes.geo1_HoloFillDark_0_2.geometry} material={materials.constant1} />
      </group>
      <mesh name="vzHumanoid" geometry={nodes.vzHumanoid.geometry} material={materials.Material} position={[-0.82, 1.86, 1.3]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh name="dome" geometry={nodes.dome.geometry} material={nodes.dome.material} position={[-1.52, 7.17, 0]} />
      <mesh name="medulaOrb" geometry={nodes.medulaOrb.geometry} material={materials.Material} position={[-0.21, 4.32, -7.13]} scale={0.15} />
      <mesh name="Sphere_Core_0" geometry={nodes.Sphere_Core_0.geometry} material={materials.Core} position={[6.1, 4.9, -1.16]} scale={2} />
      <mesh name="Sphere_Core_0001" geometry={nodes.Sphere_Core_0001.geometry} material={materials['Core.001']} position={[-5.57, -2.65, 0.93]} />
      <mesh name="Sphere_Core_0002" geometry={nodes.Sphere_Core_0002.geometry} material={materials['Core.001']} position={[-8.36, 4.16, -1.14]} />
      <mesh name="Sphere_Core_0003" geometry={nodes.Sphere_Core_0003.geometry} material={materials['Core.001']} position={[6.62, 3.04, 2.4]} />
      <mesh name="Sphere_Core_0004" geometry={nodes.Sphere_Core_0004.geometry} material={materials['Core.001']} position={[3.94, -0.96, 6.16]} />
      <mesh name="Sphere_Core_0005" geometry={nodes.Sphere_Core_0005.geometry} material={materials['Core.001']} position={[-3.02, -0.96, 8.07]} rotation={[0, -1.21, 0]} />
      <mesh name="Sphere_Core_0006" geometry={nodes.Sphere_Core_0006.geometry} material={materials['Core.001']} position={[2.77, 3.04, 7.13]} rotation={[0, -1.21, 0]} />
      <mesh name="Sphere_Core_0007" geometry={nodes.Sphere_Core_0007.geometry} material={materials['Core.001']} position={[0.17, 4.16, -4.19]} rotation={[0, -1.21, 0]} />
      <mesh name="Sphere_Core_0008" geometry={nodes.Sphere_Core_0008.geometry} material={materials['Core.001']} position={[-1.47, -2.65, -2.67]} rotation={[0, -1.21, 0]} />
      <mesh name="Sphere_Core_0009" geometry={nodes.Sphere_Core_0009.geometry} material={materials['Core.001']} position={[-1.47, 6.37, -2.96]} rotation={[0, -1.21, 0]} />
      <mesh name="Sphere_Core_0010" geometry={nodes.Sphere_Core_0010.geometry} material={materials['Core.001']} position={[0.17, 14.74, -0.61]} rotation={[0, -1.21, 0]} />
      <mesh name="Sphere_Core_0011" geometry={nodes.Sphere_Core_0011.geometry} material={materials['Core.001']} position={[0.65, 11.23, 4.02]} rotation={[0, -1.21, 0]} />
      <mesh name="Sphere_Core_0012" geometry={nodes.Sphere_Core_0012.geometry} material={materials['Core.001']} position={[-3.02, 9.62, 4.96]} rotation={[0, -1.21, 0]} />
      <mesh name="Sphere_Core_0013" geometry={nodes.Sphere_Core_0013.geometry} material={materials['Core.001']} position={[3.94, 9.62, 3.05]} />
      <mesh name="Sphere_Core_0014" geometry={nodes.Sphere_Core_0014.geometry} material={materials['Core.001']} position={[4.36, 13.63, -0.71]} />
      <mesh name="Sphere_Core_0015" geometry={nodes.Sphere_Core_0015.geometry} material={materials['Core.001']} position={[-6.41, 14.74, 2.81]} />
      <mesh name="Sphere_Core_0016" geometry={nodes.Sphere_Core_0016.geometry} material={materials['Core.001']} position={[-5.57, 7.93, -2.19]} />
      <mesh name="JNLogo" geometry={nodes.JNLogo.geometry} material={materials.Core} position={[-4.32, 7.7, 5.04]} scale={[0.5, 0.5, 0.25]} />
    </group>
  )
}

useGLTF.preload('/vzscene-transformed.glb')
